[%
 I18N = {
    FIELD_LENGTH = "${error.field}: Length is ${error.length}, should be ${error.wanted}"
    FIELD_VALUE = "${error.field}: Illegal value \"${error.value}\", should be ${error.required}"
    FIELD_VALUE_POS = "${error.field}/${error.pos}: Illegal value \"${error.value}\", should be ${error.required}"
    NOT_REPEATABLE_SUBFIELD = "${error.field}: Subfield not repeatable, used ${error.count} times"
    NOT_REPEATABLE_FIELD = "${error.field}: Field not repeatable, used ${error.count} times"
    INDICATOR = "${error.field}: Indicator ${error.indicator} is \"${error.current}\", should be ${error.valid}"
    NOT_IN_FORMAT = "${error.field}: Not used in format"
 }
%]
