[%
 I18N = {
    title = "Koha: Nalkutin: Asetukset"
    breadcrumb_home = "Koti"
    breadcrumb_plugins = "Liitännäiset"
    breadcrumb_nalkutin = "Nalkutin: Asetukset"
    label_ignore_fields = "Ohitettavat MARC-kentät"
    label_skip_encodings = "Ohitettavat koodaustasot"
    save = "Tallenna"
    header_upgrade_status = "Päivitetty"
    last_updated = "Tämä liitännäinen on päivitetty"
    upgrade_never = "Tätä liitännäistä ei ole koskaan päivitetty."
    FIELD_LENGTH = "${error.field}: pituus on ${error.length}, pitäisi olla ${error.wanted}"
    FIELD_VALUE = "${error.field}: arvo on \"${error.value}\", pitäisi olla ${error.required}"
    FIELD_VALUE_POS = "${error.field}/${error.pos}: arvo on \"${error.value}\", pitäisi olla ${error.required}"
    NOT_REPEATABLE_SUBFIELD = "${error.field}: osakenttä ei toistettava, käytetty ${error.count} kertaa"
    NOT_REPEATABLE_FIELD = "${error.field}: kenttä ei toistettava, käytetty ${error.count} kertaa"
    INDICATOR = "${error.field}: indikaattori ${error.indicator} on \"${error.current}\", pitäisi olla ${error.valid}"
    NOT_IN_FORMAT = "${error.field}: ei formaatissa"
 }
%]
