[%
 I18N = {
    FIELD_LENGTH = "${error.field}: pituus on ${error.length}, pitäisi olla ${error.wanted}"
    FIELD_VALUE = "${error.field}: arvo on \"${error.value}\", pitäisi olla ${error.required}"
    FIELD_VALUE_POS = "${error.field}/${error.pos}: arvo on \"${error.value}\", pitäisi olla ${error.required}"
    NOT_REPEATABLE_SUBFIELD = "${error.field}: osakenttä ei toistettava, käytetty ${error.count} kertaa"
    NOT_REPEATABLE_FIELD = "${error.field}: kenttä ei toistettava, käytetty ${error.count} kertaa"
    INDICATOR = "${error.field}: indikaattori ${error.indicator} on \"${error.current}\", pitäisi olla ${error.valid}"
    NOT_IN_FORMAT = "${error.field}: ei formaatissa"
 }
%]
