[%
 I18N = {
    title = "Koha: Nalkutin: Configuration"
    breadcrumb_home = "Home"
    breadcrumb_plugins = "Plugins"
    breadcrumb_nalkutin = "Nalkutin: Configuration"
    label_ignore_fields = "Ignore MARC fields"
    label_skip_encodings = "Skip Encoding Levels"
    save = "Save configuration"
    header_upgrade_status = "Upgrade status"
    last_updated = "Plugin was last upgraded on this system on"
    upgrade_never = "Plugin has never been upgraded."
    FIELD_LENGTH = "${error.field}: Length is ${error.length}, should be ${error.wanted}"
    FIELD_VALUE = "${error.field}: Illegal value \"${error.value}\", should be ${error.required}"
    FIELD_VALUE_POS = "${error.field}/${error.pos}: Illegal value \"${error.value}\", should be ${error.required}"
    NOT_REPEATABLE_SUBFIELD = "${error.field}: Subfield not repeatable, used ${error.count} times"
    NOT_REPEATABLE_FIELD = "${error.field}: Field not repeatable, used ${error.count} times"
    INDICATOR = "${error.field}: Indicator ${error.indicator} is \"${error.current}\", should be ${error.valid}"
    NOT_IN_FORMAT = "${error.field}: Not used in format"
 }
%]
